name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Analysing the code with pylint
      run: poetry run pylint src/mlb_ml_lab/ tests/ pipeline/
